### ISSUE TITLE
Using the codes for Logitech Harmony Hub

### ISSUE THREAD

**Issue by Jonn3y** [limonenblau/unitec-rfsend#1]
Hey,

i bought a Harmony Hub today and want to use the UniTec 48110 with it. 
Do you think it's possible with your bitcodes?!

Best wishes from Germany:
Jonas

**Comment by jacobmellin** [comment]
Hi,

ich schätze das wird wohl leider nicht so einfach gehen. Meine Codes folgen keinem Standard. Ich habe einfach bloß die Signale gemessen, die die mitgelieferte Fernbedienung bei Knopfdruck aussendet, und daraus die Codes abgeleitet. Allein zu dem Zweck um ein Sender-Modul mit einem Raspberry Pi so anzusteuern, dass es genau die gleichen Signale sendet, wie die Fernbedienung, und man nur noch die Codes eingeben muss.

Wenn der Harmony Hub auch auf 433Mhz sendet und du ihn genau programmieren kannst, d.h. einstellen kannst, welches Signal wie lange und mit welcher Frequenz gesendet und gepulst wird, dann sollte es möglich sein. Aber ich kann mir nicht vorstellen, dass ein Consumer-Produkt das erlaubt.

Vielleicht findest du aber eine eine andere Möglichkeit den Hub für die Steckdosen zu konfigurieren. Vielleicht bietet der Hersteller eine Konfiguration für die UniTechs an.

Meine Codes beschreiben nur, wie das Signal aussieht das von dem Sender ausgeht.

Gruß
